### ISSUE TITLE
Device lock screen

### ISSUE THREAD

**Issue by Nour833** [Open-Security-Group-OSG/HiddenEyeReborn#10]
Hi
You didn't understand me before but to understand me please search about : "LockPhish"
I hope you merge or upgrade this tool with hidden eye 
That makes hiddenphish more reliable and general for leading phishing domain.

PS : LockPhish generate link that auto detect device to open fake device lock screen (iphone,android,windows ) and it cintain keylogger to receive credentials 
❤

**Comment by sTiKyt** [comment]
You shoudn't create new issue if someone is unable to understand you... YOu have to edit previous one and fix it instead.. Btw i still don't understand what are you talking about but if you are talking about "merging" with other tool - that's impossible. Closing here.
