### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by alari73512** [Open-Security-Group-OSG/HiddenEyeReborn#12]
I know were dumb but you should leave an installation guide or how to launch it. Thank you!

**Comment by E1MWM13** [comment]
> I know were dumb but you should leave an installation guide or how to launch it. Thank you!

its not ready to use yet

**Comment by alari73512** [comment]
Okay, but when do you plan on releasing it? This week, month, year?

**Comment by sTiKyt** [comment]
@alari73512 Somewhere in next decade

**Comment by alari73512** [comment]
XD yee, but seriously? :)

**Comment by sTiKyt** [comment]
@alari73512 Seriously? Want it to release faster - contribute...

**Comment by sTiKyt** [comment]
@alari73512 I'm doing it all solo. Our community doesn't seem to help at all… No contributions, no donations, no learners or testers, no translators, no documentation writers, no-one. I do it all solo, so I have NO IDEA how long it will take. That's my honest answer. I have to live REAL LIFE as well, can't just code 24/7 and spend all my time working on non-profit open source app with low demand and dead community

**Comment by Morsmalleo** [comment]
> @alari73512 I'm doing it all solo. Our community doesn't seem to help at all… No contributions, no donations, no learners or testers, no translators, no documentation writers, no-one. I do it all solo, so I have NO IDEA how long it will take. That's my honest answer. I have to live REAL LIFE as well, can't just code 24/7 and spend all my time working on non-profit open source app with low demand and dead community, I have to pay for bills and eat food same as all you do...

Thats pretty sad man I'll contribute as much as I can

**Comment by sTiKyt** [comment]
Duplicate of #11
