### ISSUE TITLE
Make a better readme

### ISSUE THREAD

**Issue by hello-lab** [Open-Security-Group-OSG/HiddenEyeReborn#18]
Please write the commands needed to run it.

**Comment by sTiKyt** [comment]
@hello-lab You can't run it, close your issue and keep waiting.. Didn't you see it's version or something?

**Comment by sTiKyt** [comment]
990c823e93c85f084225fce995fbe59dd2dda523

**Comment by sTiKyt** [comment]
Duplicate of #11
