### ISSUE TITLE
Running process

### ISSUE THREAD

**Issue by Defencebd** [Open-Security-Group-OSG/HiddenEyeReborn#21]
Plz give details abt installation...

**Comment by sTiKyt** [comment]
Learn to read README.md...

**Comment by Defencebd** [comment]
I think this is incomplete... After Opening directory can't run
setup.py....then try to run hiddeneye_reborn....but it says "Success, you
can access this via terminal!
Hey, if you can - contact that lazy developer and make him code! Would be
glad if you contribute, as well..."
What next....

**Comment by sTiKyt** [comment]
Duplicate of #11
