### ISSUE TITLE
Setup github actions to automatically build package on tagged commit

### ISSUE THREAD

**Issue by sTiKyt** [Open-Security-Group-OSG/HiddenEyeReborn#22]
Remind me guys, remind me...

Notes:

Reference and example info: https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#creating-a-workflow-definition

Keep in mind: Replace pep517 approach with default one

Commands i'm too lazy to finally memorize... 

sudo bash -cl "/home/nameless/Work/Development/OSS/HiddenEyeReborn/venv/bin/python /home/nameless/Work/Development/OSS/HiddenEyeReborn/setup.py sdist bdist_wheel"

======================================
twine upload dist/*

#REMEMBER 
On ArchLinux you need to use sudo pip when installing (Probably, gotta do more tests)

**Comment by Blacksorceres** [comment]
el ejecutable .py solo dice unas lineas de agradecimiento , no hace nada, ?que tipo de cosa es esta ? ... no hay manera de usar.,

**Comment by sTiKyt** [comment]
@Blacksorceres English only please

**Comment by jujodemula00** [comment]
when opening it only says a few words of thanks it does not work you can correct it

**Comment by 4tome** [comment]
That's because they're still working on the project

**Comment by jujodemula00** [comment]
thanks friend I didn't know

**Comment by zerozero5ive** [comment]
Thank you
