### ISSUE TITLE
execute hiddeneye_reborn

### ISSUE THREAD

**Issue by tusharsharma082001** [Open-Security-Group-OSG/HiddenEyeReborn#26]
how  to run the program hiddeneye_reborn.py

**Comment by GoldenFroze** [comment]
@tusharsharma082001 Learn how to read first then comeback here

**Comment by sTiKyt** [comment]
Closed, reported as spam

**Comment by Morsmalleo** [comment]
You can't its still in development, I'm sure the author of this project is working hard on it

**Comment by sTiKyt** [comment]
Duplicate of #11
