### ISSUE TITLE
How do I open HiddenEye?

### ISSUE THREAD

**Issue by CysticX** [Open-Security-Group-OSG/HiddenEyeReborn#27]
Forgive my ignorance, because it is prob something very obvious. I have installed everything pretty smoothly but I am clueless on how to open this HE version. I opened the first original one easily but this hiddeneye doesnt really provide any context for opening the hiddeneye screen to see all your phishing options and whatnot. what do i put in my terminal to activate this?

**Comment by sTiKyt** [comment]
Nothing. This is under development.

**Comment by comming-soon-official** [comment]
release after it finish users are confused to how to use HE version

**Comment by sTiKyt** [comment]
It's not RELEASED, genius.

**Comment by Morsmalleo** [comment]
> It's not RELEASED, genius.

well thanks for nothing GENIUS

**Comment by sTiKyt** [comment]
@Morsmalleo well, you are welcome, skid

**Comment by Morsmalleo** [comment]
> @Morsmalleo well, you are welcome, skid

My apologies mate, I didn't mean to be so rude, having a s**t life at the moment and the only that helps is coding, cybersec and malware analysis, it was wrong of me to be so rude and I do apologise, it will not happen ever again

**Comment by sTiKyt** [comment]
Duplicate of #11

**Comment by m3dus444** [comment]
Hi, got same problem as CysticX, forgive my ignorance i'm kind of a beginer. Usually i install all frameworks like that without any issue, but i didn't understand how to run HE:RE. sTiKyt said it wasn't released yet, it is still true ? If not, how can i run it ?
Thanks!
