### ISSUE TITLE
how to start

### ISSUE THREAD

**Issue by apt-nishant69** [Open-Security-Group-OSG/HiddenEyeReborn#31]
i downloaded it succesfully but i dont know how to launch the script

**Comment by Morsmalleo** [comment]
you can't its still in development

**Comment by hokd2905** [comment]
@Morsmalleo is it still in development?

**Comment by Morsmalleo** [comment]
Yes it is still in development, I'm doing the best i can to the help the
dev on this project

**Comment by sTiKyt** [comment]
Duplicate of #11
