### ISSUE TITLE
HOW do I run the script ?

### ISSUE THREAD

**Issue by TuaPai** [Open-Security-Group-OSG/HiddenEyeReborn#33]
When I am trying to run the script it says-
"Success, you can access this via terminal!"
How do I access it via terminal?

**Comment by Morsmalleo** [comment]
It hasn't be released or finished yet according to the developer :(

**Comment by networkadel** [comment]
i think The developer is not gay although my friend said he is.

**Comment by graysuit** [comment]
> 
> 
> i think The developer is not gay although my friend said he is.

Don't be rude. Respect open source developers. They are doing it for you free without getting any return.

**Comment by sTiKyt** [comment]
> i think The developer is not gay although my friend said he is.

Well, first of all, no, i'm straight. 
Secondly - this is offtopic and not related to this and most of other projects on github, if you don't respect me - i don't respect you, here goes your ban.

**Comment by Morsmalleo** [comment]
I know this is off topic but i have to say something, that dude you blocked was nothing but a rude a**hole, jeez some people have no respect, you handled that well @sTiKyt very well

**Comment by sTiKyt** [comment]
Duplicate of #11
