### ISSUE TITLE
How to launch HiddenEyeReborn after installation

### ISSUE THREAD

**Issue by Morsmalleo** [Open-Security-Group-OSG/HiddenEyeReborn#34]
Can you please tell us how to launch HiddenEyeReborn!

I have pip installed HE: RE but I always get the same thing when trying to run it

**"Success, you can access this via terminal!
Hey, if you can - contact that lazy developer and make him code! Would be glad if you contribute, as well..."**

I have even git cloned the repository and pip installed the requirements.txt which went fine, however upon running the setup.py file i get this coming up in the terminal

**"usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]**
  **or: setup.py --help [cmd1 cmd2 ...]**
   **or: setup.py --help-commands**
   **or: setup.py cmd --help**

**error: no commands supplied"**

and everytime I cd into the hiddeneye_reborn folder inside the HiddenEyeReborn repository, and launch the hiddeneye_reborn.py file via **python3 hiddeneye_reborn.py**

I still get the same message (I KNOW THIS ISN'T AN ERROR MESSAGE)

**"Success, you can access this via terminal!
Hey, if you can - contact that lazy developer and make him code! Would be glad if you contribute, as well..."**

a little feedback and some advice on how to launch this application would be helpful, thanks mate :)

**Comment by Morsmalleo** [comment]
Never mind HiddenEye-Reborn won't work because it hasn't been released or finished yet unsurprisingly

**Comment by sTiKyt** [comment]
Duplicate of #11

**Comment by RumethHack** [comment]
> Can you please tell us how to launch HiddenEyeReborn!
> 
> I have pip installed HE: RE but I always get the same thing when trying to run it
> 
> **"Success, you can access this via terminal! Hey, if you can - contact that lazy developer and make him code! Would be glad if you contribute, as well..."**
> 
> I have even git cloned the repository and pip installed the requirements.txt which went fine, however upon running the setup.py file i get this coming up in the terminal
> 
> **"usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]**
> **or: setup.py --help [cmd1 cmd2 ...]**
> **or: setup.py --help-commands**
> **or: setup.py cmd --help**
> 
> **error: no commands supplied"**
> 
> and everytime I cd into the hiddeneye_reborn folder inside the HiddenEyeReborn repository, and launch the hiddeneye_reborn.py file via **python3 hiddeneye_reborn.py**
> 
> I still get the same message (I KNOW THIS ISN'T AN ERROR MESSAGE)
> 
> **"Success, you can access this via terminal! Hey, if you can - contact that lazy developer and make him code! Would be glad if you contribute, as well..."**
> 
> a little feedback and some advice on how to launch this application would be helpful, thanks mate :)

Me tooo want to know...please?? whats the meaning..?and how am i supposed to launch it??
