### ISSUE TITLE
How To Run HiddenEye-Reborn

### ISSUE THREAD

**Issue by DrunkenDroid** [Open-Security-Group-OSG/HiddenEyeReborn#43]
How do i run it? it keeps saying:
Success, you can access this via terminal!

I have no other terminal except Kali linux & Command Promt (If there is for Cmd please tell me.)

Or maybe it hasn't yet finished?

**Comment by sTiKyt** [comment]
Or, maybe, you should learn to look at closed issues before making new ones.

**Comment by sTiKyt** [comment]
Duplicate of #11
