### ISSUE TITLE
Can't Open this Tools

### ISSUE THREAD

**Issue by hkranishsharma** [Open-Security-Group-OSG/HiddenEyeReborn#47]
can anyone please guide me on how to run this tool in kali linux.

**Comment by sTiKyt** [comment]
@hkranishsharma Learn to read, best skill ever, highly recommend it

**Comment by lazengann86** [comment]
Yeah some instructions on it would be helpful, I just get this generic "this is running" type of message

**Comment by sTiKyt** [comment]
@lazengann86 Yeah, some effort to click at "tags" or "releases" would be helpful as well, but people don't want to put that effort in

If you want you could check what those say and add info to README.md

Have fun

**Comment by lazengann86** [comment]
@hkranishsharma Last notes from Oct 2020 suggest "This project isn't ready for end-user, you shouldn't be installing this package unless you know what you are doing. I warned you."

@sTiKyt it actually took more character to write your little sass than to write a quick explanation lol.

**Comment by sTiKyt** [comment]
@lazengann86 Last time i checked this project had 47 issues asking "how do i use this tool"

**Comment by sTiKyt** [comment]
Duplicate of #11

**Comment by lazengann86** [comment]
@sTiKyt I saw, I saw all the older posts, maybe making the "This is not working yet" note easier to find my help minimize the flooding of those messages.

**Comment by sTiKyt** [comment]
@lazengann86 If you want you can come talk on our telegram

**Comment by sTiKyt** [comment]
@sTiKyt https://t.me/darksecofficial

**Comment by joel9966** [comment]
Just shoot me an email at ***@***.***
