### ISSUE TITLE
syntax error near unexpected token `|'

### ISSUE THREAD

**Issue by Anonymous6667498666** [Open-Security-Group-OSG/HiddenEyeReborn#51]
Requirement already satisfied: hiddeneye-reborn in /data/data/com.termux/files/usr/lib/python3.9/site-packages (0.0a1.dev4)
Requirement already satisfied: pywebcopy in 
/data/data/com.termux/files/usr/lib/python3.9/site-p
 

Now how to run the tool?

**Comment by sTiKyt** [comment]
@Anonymous6667498666 Did you try learning to read?

**Comment by Anonymous6667498666** [comment]
What? How can i run this tool sir please help with this after this all process it shows nothing is there any command to run this tool im.using termux

**Comment by Anonymous6667498666** [comment]
> @Anonymous6667498666 Did you try learning to read?

I can't understand ? 
After process how to locate or run the tools there is no directory named hiddeneyereborn or something how to use now?

**Comment by sTiKyt** [comment]
@Anonymous6667498666 Read description of GitHub repository or any of releases..

**Comment by Anonymous6667498666** [comment]
> @Anonymous6667498666 Read description of GitHub repository or any of releases..

Executed this command  pip install hiddeneye-reborn 
Now what? To do ? There is no other command mention in your description

**Comment by Anonymous6667498666** [comment]
> @Anonymous6667498666 Read description of GitHub repository or any of releases..

Success, you can access this via terminal!
Hey, if you can - contact that lazy developer and make him code! Would be glad if you contribute, as well...

**Comment by Anonymous6667498666** [comment]
So its not available yet how to use the tool?

**Comment by sTiKyt** [comment]
> > @Anonymous6667498666 Read description of GitHub repository or any of releases..
> 
> Executed this command pip install hiddeneye-reborn
> Now what? To do ? There is no other command mention in your description

![image](https://user-images.githubusercontent.com/35602029/123283355-fff0d400-d513-11eb-9984-b9ae7ac07d2f.png)
![image](https://user-images.githubusercontent.com/35602029/123283421-0d0dc300-d514-11eb-9d15-7a9679514221.png)

**Comment by sTiKyt** [comment]
Duplicate of #11

**Comment by sTiKyt** [comment]
Banned for duplicating #11

**Comment by Anonymous6667498666** [comment]
Wtf
