### ISSUE TITLE
How to delete it from termux?

### ISSUE THREAD

**Issue by Paradox-2** [Open-Security-Group-OSG/HiddenEyeReborn#52]
I have installed this tool but not working. How to delete this tool?

**Comment by MatrixOP** [comment]
Navigate to the file and use rm -rf toolName

**Comment by MatrixOP** [comment]
To navigate use cd command

**Comment by sTiKyt** [comment]
@MatrixOP Jeez... Terrible suggestion.. It's a pip package, genius, just use pip to delete it

**Comment by MatrixOP** [comment]
rm -rf toolName this one would work too right?
