### ISSUE TITLE
Termux Setup 

### ISSUE THREAD

**Issue by viprdiamondent** [Open-Security-Group-OSG/HiddenEyeReborn#53]
Hello Guys Thank u for an awesome Repository much is appreciated, I had install hidden eye reborn on my androids through termux and I ran into a small error, I ran 

python3 hiddeneye_reborn.py   

In terminal and it just sed success contact developers lol is there a way around this?? I also installed the old hidden eye it worked but this is the newer version can't wait to hear from u guys lol

**Comment by Deligt4l** [comment]
> Hello Guys Thank u for an awesome Repository much is appreciated, I had install hidden eye reborn on my androids through termux and I ran into a small error, I ran 
> 
> python3 hiddeneye_reborn.py   
> 
> In terminal and it just sed success contact developers lol is there a way around this?? I also installed the old hidden eye it worked but this is the newer version can't wait to hear from u guys lol 
> 

Pls can you give commands for the installation of hiddeneyereborn. Does it really work after that command?

**Comment by sTiKyt** [comment]
Solved by replacing message with "THIS IS NOT PRODUCTION READY, STOP MAKING USELESS ISSUES PLEASE"

**Comment by Skjnior** [comment]
at home the hidden eye does not take I installed all the tools but impossible
