### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by shreyu987** [Open-Security-Group-OSG/HiddenEyeReborn#54]
It isn't install.
Is it working anymore

**Comment by graysuit** [comment]
@shreyu987 
In about description, its clearly written:
`HiddenEye with completely new codebase and better features set, `**NOT READY FOR END USER**`, You will be banned for duplicating issue #11 immediately!` 

https://github.com/Open-Security-Group-OSG/HiddenEyeReborn/issues/11

Anyway, enjoy your bane soon ! lol.

**Comment by sTiKyt** [comment]
Duplicate of #11, enjoy your ban, kid.
