### ISSUE TITLE
Cant I Use Now?

### ISSUE THREAD

**Issue by Artur-Tretiak2002** [Open-Security-Group-OSG/HiddenEyeReborn#56]
@sTiKyt @karniv0re-cyber

**Comment by sTiKyt** [comment]
Duplicate of #11, why are you duplicating this... bruh..

**Comment by sTiKyt** [comment]
![image](https://user-images.githubusercontent.com/35602029/130071653-06f9871b-c108-4a1b-b973-621638255f71.png)
