### ISSUE TITLE
After installation, It Wont run

### ISSUE THREAD

**Issue by aizaz321** [Open-Security-Group-OSG/HiddenEyeReborn#60]
![HIdden eye](https://user-images.githubusercontent.com/64736413/130592640-9e385087-8a76-4ef1-8196-570f5cc8dea9.JPG)

I just folllowed the old hidden run installation method. now i am getting following error as shown in figure.

**Comment by Skjnior** [comment]
@aizaz321 what code did you use to activate ??

**Comment by aizaz321** [comment]
> @aizaz321 what code did you use to activate ??

what you mean?. i just want to execute hidden eye reborn but it didnt execute. it show errors. you can see my command to execute hidden eye reborn

**Comment by Skjnior** [comment]
@aizaz321 me too it is the same thing but I wanted to know the code that you typed for the execution maybe you made a mistake

**Comment by sTiKyt** [comment]
Imagine following old instructions for new software.. Those are two completely different projects

**Comment by Skjnior** [comment]
So you show us the new method please ??

**Comment by Morsmalleo** [comment]
This is not ready for END USER in other words this is still in development
