### ISSUE TITLE
ModuleNotFoundError: No module named 'app_logging'

### ISSUE THREAD

**Issue by ELREYNINFA** [Open-Security-Group-OSG/HiddenEyeReborn#75]
I installed HiddenEyeReborn with the command '' pip install hiddeneye-reborn'' in kali linux
and when i put the command hiddeneye, i see this error : 
Traceback (most recent call last):
  File "/usr/local/bin/hiddeneye", line 5, in <module>
    from hiddeneye_reborn.hiddeneye_reborn import main
  File "/usr/local/lib/python3.9/dist-packages/hiddeneye_reborn/hiddeneye_reborn.py", line 2, in <module>
    from app_logging.default_logging import logging, log, set_logging_config
ModuleNotFoundError: No module named 'app_logging'

**Comment by Morsmalleo** [comment]
It's still in development, read the info on the main page!

**Comment by Morsmalleo** [comment]
You also haven't searched the closed issues either because this is a direct duplicate of issue #73

**Comment by graysuit** [comment]
@ELREYNINFA 
Now 1 step you can take, is ENJOY (ban)
![Capture](https://user-images.githubusercontent.com/54432616/147087442-2c038f8b-21a4-4716-befd-8f936d7158e1.PNG)

**Comment by ELREYNINFA** [comment]
Sorry i am stupid. @graysuit @Morsmalleo

**Comment by sTiKyt** [comment]
Solved tho

**Comment by Morsmalleo** [comment]
> Solved tho

Awesome! 😁
