### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by AgentP5547** [Open-Security-Group-OSG/HiddenEyeReborn#82]
Hey there,
When I run _chmod +x setup.py_ and _./setup.py_
I get this following error:

`import-im6.q16:` attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421.
./setup.py: line 6: __author__: command not found
./setup.py: line 8: __version__: command not found
./setup.py: line 9: __package_name__: command not found
./setup.py: line 10: __description__: command not found
./setup.py: line 11: __python_requires__: command not found
./setup.py: line 12: __install_requires__: command not found
./setup.py: line 13: syntax error near unexpected token `('
./setup.py: line 13: `__data_files__ = [("", `["LICENSE"])]'`

**Comment by sTiKyt** [comment]
You are not supposed to run this script manually, it's for pypi
